config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: {omniauth_callbacks: 'omniauth_callbacks' }

  scope "(:locale)", locale: /en|bg/ do

    mount Ckeditor::Engine => '/ckeditor'

    resources :articles

    scope '/admin' do
      resources :users
    end

    match '/contacts', to: 'contacts#new', via: 'get'
    resources 'contacts', only: [:new, :create]

    get '/pages/:page' => 'pages#show', as: :pages

    root 'pages#show', page: 'home'

  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  before_create :set_default_language

  LANGUAGES = { BG: 'bulgarian', EN: 'english' }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  # Relationships
  has_many :articles

  # Validations
  validates :username, presence: true, length: { in: 4..39 }, uniqueness: {case_sensitive: false}
  validates :username, format: { with: /\A[a-zA-Z0-9]+[a-zA-Z\-0-9]*\z/, message: 'Username may only contain alphanumeric characters or dashes and cannot begin with a dash' }

  # Virtual attribute for authenticating by either username or email
  # This is in addition to a real persisted field like 'username'
  attr_accessor :login

  def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end

  # Overriding the find_for_database_authentication method allows us to edit database authentication
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(['lower(username) = :value OR lower(email) = :value', { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.nickname || auth.info.name.gsub(' ', '-')
      user.email = auth.info.email
    end
  end

  def self.new_with_session(params, session)
    if session['devise.user_attributes']
      new session["devise.user_attributes"] do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end

  private

    def set_default_language
      self.language ||= 'BG'
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  load_and_authorize_resource

  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /admin/users
  # GET /admin/users.json
  def index
    @users = User.all
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
  end

  # GET /admin/users/new
  def new
    @user = User.new
  end

  # GET /admin/users/1/edit
  def edit
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/users/1
  # PATCH/PUT /admin/users/1.json
  def update

    if user_params[:password].blank?
      user_params.delete(:password)
      user_params.delete(:password_confirmation)
    end

    # https://github.com/plataformatec/devise/wiki/How-To%3a-Allow-users-to-edit-their-account-without-providing-a-password
    successfully_updated = if needs_password?(@user, user_params)
                             @user.update(user_params)
                           else
                             @user.update_without_password(user_params)
                           end

    respond_to do |format|
      if successfully_updated
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

    #respond_to do |format|
    #  if @user.update(user_params)
    #    format.html { redirect_to @user, notice: 'User was successfully updated.' }
    #    format.json { render :show, status: :ok, location: @user }
    #  else
    #    format.html { render :edit }
    #    format.json { render json: @user.errors, status: :unprocessable_entity }
    #  end
    #end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    #params[:user]
    params.require(:user).permit(:email, :username, :password, :password_confirmation, :language)
  end

  # https://github.com/plataformatec/devise/wiki/How-To%3a-Allow-users-to-edit-their-account-without-providing-a-password
  def needs_password?(user, params)
    params[:password].present?
  end


end

app/helpers/users_helper.rb
module UsersHelper

  def avatar_url(user)
    if user.avatar_url.present?
      user.avatar_url
    else
      #default_url = "#{root_url}images/guest.png"
      default_url = 'https://raw.githubusercontent.com/railscasts/244-gravatar/master/grav/public/images/guest.png'
      gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
      "http://gravatar.com/avatar/#{gravatar_id}.png?s=48&d=#{CGI.escape(default_url)}"
    end
  end

end

app/views/users/_form.html.erb
<%= simple_form_for(@user, html: { class: 'form-horizontal' },wrapper: :horizontal_form) do |f| %>
<fieldset>
  <%= f.input :username, autofocus: true, placeholder: 'myname-89' %>
  <%= f.input :email, placeholder: 'mymail@mail.com' %>
  <%= f.input :password, autocomplete: 'off', placeholder:'eg. X8df!90EO' %>
  <%= f.input :password_confirmation, autocomplete: 'off',  placeholder:'eg. X8df!90EO' %>
  <%= f.input :language, collection: User::LANGUAGES.invert.sort, :selected => @user.language %>

  <div class='form-group'>
  <div class='col-sm-2'></div>
  <div class='form-actions col-sm-9'>
    <%= button_tag(type: 'submit', class: 'btn btn-primary') do %>
        <% if @user.new_record? %>
        <i class='icon-user-add'></i> Create User
        <% else %>
        <i class='icon-edit-alt'></i> Save
        <% end %>
    <% end %>
    <%= link_to users_path, data: { confirm: 'Are you sure?' },class: 'btn btn-danger' do %>
        <i class='icon-trash'></i> Cancel
    <% end %>
  </div>
  </div>
</fieldset>
<% end %>

app/views/users/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><strong>Editing user</strong></h3>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

<%= link_to @user, class: 'btn btn-success' do %>
    <i class='icon-list-alt'></i> Show
<% end %>

<%= link_to users_path, class: 'btn btn-default btn-primary' do %>
    <i class='icon-left-big'></i> Back
<% end %>

app/views/users/index.html.erb
<div class='table-responsive'>
    <table class='table table-striped'>
      <thead>
      <tr>
        <th></th>
        <th>Login</th>
        <th>Email</th>
        <th>Is Admin</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @users.each do |user| %>
          <tr>
            <td><%= image_tag avatar_url(user) %></td>
            <td><%= user.username %></td>
            <td><%= user.email %></td>
            <td><%= user.is_admin? ? 'Yes' : 'No' %></td>
            <td>
              <%= link_to user, class: 'btn btn-success' do %>
                  <i class='icon-list-alt'></i> Show
              <% end %>
              <%= link_to edit_user_path(user), class: 'btn btn-warning' do %>
                  <i class='icon-pencil'></i> Edit
              <% end %>
              <% if user.is_admin %>
                  <%= link_to user,method: :delete,data: { confirm: 'Are you sure?' },class: 'btn btn-danger disabled' do %>
                      <i class='icon-trash'></i> Destroy
                  <% end %>
              <% else %>
                  <%= link_to user,method: :delete,data: { confirm: 'Are you sure?' },class: 'btn btn-danger' do %>
                      <i class='icon-trash'></i> Destroy
                  <% end %>
              <% end %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
</div>

<%= link_to new_user_path, class: 'btn btn-primary' do %>
    <i class='icon-user-add'></i> New User
<% end %>

app/views/users/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><strong>New user</strong></h3>
  </div>
  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

<%= link_to users_path, class: 'btn btn-default btn-primary' do %>
    <i class='icon-left-big'></i> Back
<% end %>

app/views/users/show.html.erb
<div class='panel panel-default'>
  <div class='panel-heading'>User Details</div>
  <div class='panel-body'>

    <!-- Nav tabs -->
    <ul class='nav nav-tabs' role='tablist'>
      <li class='active'><a href='#profile' role='tab' data-toggle='tab'><i class='icon-user-4'></i>Profile</a></li>
      <li><a href='#articles' role='tab' data-toggle='tab'><i class='icon-article-alt-1'></i>Articles</a></li>
      <li><a href='#logs' role='tab' data-toggle='tab'><i class='icon-calendar-7'></i>Logs</a></li>
      <li><a href='#others' role='tab' data-toggle='tab'><i class='icon-info-circled'></i>Other</a></li>
    </ul>

    <!-- Tab panes -->
    <div class='tab-content'>
      <div class='tab-pane active' id='profile'>
        <br />
        <div class='table-responsive'>
          <table class='table table-striped table-bordered table-condensed'>
            <thead>
              <tr>
                <th colspan='2'><span style='visibility:hidden;'>Hidden Text</span></th>
              </tr>
            </thead>
            <tbody>
            <% if can? :manage, User %>
              <tr>
                <td><strong>User ID</strong></td>
                <td><%= @user.id %></td>
              </tr>
            <% end %>
              <tr>
                <td><strong>Gravatar</strong></td>
                <td><%=image_tag avatar_url(@user)%></td>
              </tr>
              <tr>
                <td><strong>Login</strong></td>
                <td><%= @user.username %></td>
              </tr>
              <tr>
                <td><strong>Email</strong></td>
                <td><%= @user.email %></td>
              </tr>
            <tr>
              <td><strong>Language</strong></td>
              <td><img src="/images/blank.png" class="flag flag-<%= @user.language.downcase %>" alt="<%= @user.language %>" /></td>
            </tr>
            <% if can? :manage, User %>
              <tr>
                <td><strong>Is Admin</strong></td>
                <td><%= @user.is_admin? ? 'Yes' : 'No' %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <div class='tab-pane' id='articles'>
        <br />
        <div class='table-responsive'>
          <table class='table table-striped table-bordered table-condensed'>
            <thead>
            <tr>
              <th><strong>Name</strong></th>
              <th><strong>Created at</strong></th>
              <th><strong>Last Modified at</strong></th>
            </tr>
            </thead>
            <tbody>
            <% articles = get_articles_by_id(@user.id) %>
            <% if articles.empty? %>
                <tr>
                  <td colspan='3'><strong>No articles found.</strong></td>
                </tr>
            <% else %>
                <% articles.each do |article| %>
                    <tr>
                      <td><%= link_to article.name, article_path(article.id) %></td>
                      <td><%= article.created_at %></td>
                      <td><%= article.updated_at %></td>
                    </tr>
                <% end %>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
      <div class='tab-pane' id='logs'>
        <br />
        <div class='table-responsive'>
          <table class='table table-striped table-bordered table-condensed'>
            <thead>
              <tr>
                <th colspan='2'><span style='visibility:hidden;'>Hidden Text</span></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>Created at</strong></td>
                <td><%= @user.created_at %></td>
              </tr>
              <tr>
                <td><strong>Updated at</strong></td>
                <td><%= @user.updated_at %></td>
              </tr>
              <tr>
                <td><strong>Last sign in at</strong></td>
                <td><%= @user.last_sign_in_at %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class='tab-pane' id='others'>
        <br />
        <div class='table-responsive'>
          <table class='table table-striped table-bordered table-condensed'>
            <thead>
              <tr>
                <th colspan='2'><span style='visibility:hidden;'>Hidden Text</span></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>Sing In IP address</strong></td>
                <td><%= @user.current_sign_in_ip %></td>
              </tr>
              <tr>
                <td><strong>Provider</strong></td>
                <td><%= @user.provider %></td>
              </tr>
              <tr>
                <td><strong>Sign in count</strong></td>
                <td><%= @user.sign_in_count %></td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<% if can? :manage, User %>
    <%= link_to edit_user_path(@user), class: 'btn btn-warning' do %>
        <i class='icon-pencil'></i> Edit
    <% end %>

    <%= link_to users_path, class: 'btn btn-default btn-primary' do %>
        <i class='icon-left-big'></i> Back
    <% end %>
<% end %>